services:
  backend:
    env_file:
      - ./backend/.env.local
    build: ./backend
    ports:
      - "9000:9000"
    volumes:
      - ./backend:/usr/src/app
    command: npx nodemon src/index.js

  frontend:
    env_file:
      - ./frontend/.env.local
    build: ./frontend
    ports:
      - "8000:8000"
    volumes:
      - ./frontend:/usr/src/app
    command: npm start
    depends_on:
      - backend
